export const REGULATIONS_SELECT_REQUEST = 'REGULATIONS_SELECT_REQUEST'
export const REGULATIONS_SELECT_SUCCESS = 'REGULATIONS_SELECT_SUCCESS'
export const REGULATIONS_SELECT_FAIL = 'REGULATIONS_SELECT_FAIL'

export const DIMENSIONS_UPDATE_REQUEST = 'DIMENSIONS_UPDATE_REQUEST'
export const DIMENSIONS_UPDATE_SUCCESS = 'DIMENSIONS_UPDATE_SUCCESS'
export const DIMENSIONS_UPDATE_FAIL = 'DIMENSIONS_UPDATE_FAIL'
